### ISSUE TITLE
jaco v0.9.5?

### ISSUE THREAD

**Issue by adamk33n3r** [RKGman/fire-beats#15]
Hey, I know this isn't really an "issue" but I'm looking to add mp3 support to my plugin and I noticed that you have v0.9.5 but I only see v0.9.4 online. Where did you get this? Looking at your commits it looks like you may have built it yourself? Just curious what the story is behind this version! It looks like it has extra methods like `add(File file)` etc that v0.9.4 doesn't have.

**Comment by adamk33n3r** [comment]
I actually did find a v.0.10.2 at https://sourceforge.net/p/jacomp3player/code/HEAD/tree/JACo%20MP3%20Player%20v3/dist/ so I'm also curious what the differences are there.

**Comment by RKGman** [comment]
I honestly cannot remember how I came to that specific build, sorry! I do vaguely remember having to read through some source code and figure out what was going on though.  There was probably that missing method like you mentioned.

**Comment by adamk33n3r** [comment]
Ok no problem, thanks for the response :)
