### ISSUE TITLE
OSRSBeatz

### ISSUE THREAD

**Issue by jdmalter** [RKGman/fire-beats#4]
Add a note in a **highly visible** location which describes your affiliation to OSRSBeatz with a link to their [Patreon](https://patreon.com/OSRSBeatz?utm_medium=social&utm_campaign=creatorshare). A non-trivial fraction of your playlist tracks is produced by them.

**Comment by RKGman** [comment]
Not sure I'll be able to add the Patreon link, but there is a note in the chat when a song plays to give credit to the artist.
